spring.application.name=UberApp

# DB properties
spring.datasource.url=jdbc:postgresql://${DB_HOST_URL}:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secretkey=${JWT_SECRET_KEY}

#smtp config
